branches:
  only:
    - master
    - develop
environment:
  release_name: "oxipay-magento-2.x_v%appveyor_build_version%.zip"
before_build:
  - ps: (Get-Content Humm/HummPaymentGateway/Gateway/Config/Config.php).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content Humm/HummPaymentGateway/Gateway/Config/Config.php
build_script:
  - ps: Invoke-Expression "7z a $env:release_name"
artifacts:
  - path: $(release_name)
    name: $(appveyor_build_version)
    type: zip
deploy:
  release: v$(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: UaYGIzw09m+5DkdlA5zDuCr5x71z0KFvgquQhFSMxuJiUmltfok5GuMk8aGpG5U6
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@oxipay.com.au
  - provider: Slack
    auth_token:
      secure: lgjOGAi/xfra+Ezjg696zGwfMyEivWbNo6ho9GwbeQConO2VwxX2txxjWrZVqAaxTtI7y/ODz0HG3uMfIiM5wF2Fa0KsT8I+KL7PW9BbzpQ=
    channel: '#alerts'
