branches:
  only:
    - master
    - develop
environment:
  tag_name: "%APPVEYOR_REPO_TAG_NAME%"
  release_name: "humm-magento-2.x_v%appveyor_repo_tag_name%.zip"
before_build:
  - ps: (Get-Content Gateway/Config/Config.php).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content Gateway/Config/Config.php
build_script:
  - ps: Invoke-Expression "rm .\.git\, .\.gitignore, .\appveyor.yml -r -fo"
  - ps: Invoke-Expression "mkdir -p Humm/HummPaymentGateway"
  - ps: Invoke-Expression "ls -Exclude Humm | mv -Destination Humm/HummPaymentGateway"
  - ps: Invoke-Expression "7z a $env:release_name Humm"
artifacts:
  - path: $(release_name)
    name: $(tag_name)
    type: zip
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: UaYGIzw09m+5DkdlA5zDuCr5x71z0KFvgquQhFSMxuJiUmltfok5GuMk8aGpG5U6
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@shophumm.com.au
  - provider: Slack
    auth_token:
      secure: lgjOGAi/xfra+Ezjg696zGwfMyEivWbNo6ho9GwbeQConO2VwxX2txxjWrZVqAaxTtI7y/ODz0HG3uMfIiM5wF2Fa0KsT8I+KL7PW9BbzpQ=
    channel: '#alerts'
